# Generated by Django 5.1.4 on 2025-02-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('meaning', models.CharField(max_length=200)),
                ('example', models.CharField(max_length=200)),
            ],
        ),
    ]
